New org perms
CoasterFan5/Clubsaurus pull request #102
Opened 2024-02-15 20:43 UTC by CoasterFan5

2024-02-16 12:56 UTC, LeoDog896 requested changes

2024-02-16 13:47 UTC, CoasterFan5 commented on src/routes/(app)/org/[id=integer]/settings/members/+page.svelte
> +	let searchBox: SearchBox<(typeof data)['roles'][number]>;
I don't know what you mean here.

2024-02-16 13:49 UTC, CoasterFan5 commented on src/routes/(app)/org/[id=integer]/club/[clubId]/+layout.server.ts
> +					AND: {
Yes

2024-02-16 13:51 UTC, CoasterFan5 commented on .vscode/settings.json
> +	"cSpell.words": ["orgid"]
Funnily, you made a typo in the link: https://github.com/crate-ci/typos
*using this as a personal note

2024-02-16 14:15 UTC, CoasterFan5 commented on src/routes/(app)/org/[id=integer]/club/[clubId]/settings/members/+page.server.ts
> +	const { canTransferOwner } = await validateUser(cookies.get('session'), params);
What does this even mean?

2024-02-16 15:21 UTC, LeoDog896 commented on src/routes/(app)/org/[id=integer]/club/[clubId]/settings/members/+page.server.ts
> +	const { canTransferOwner } = await validateUser(cookies.get('session'), params);
good job

2024-02-16 15:21 UTC, LeoDog896 commented on src/routes/(app)/org/[id=integer]/settings/members/+page.svelte
> +	let searchBox: SearchBox<(typeof data)['roles'][number]>;
good job

2024-02-17 00:01 UTC, LeoDog896 approved these changes

2024-02-20 12:21 UTC, merged