feat: calendar colors
CoasterFan5/Clubsaurus pull request #127
Opened 2024-03-12 23:58 UTC by LeoDog896

Closes #58

2024-03-14 00:59 UTC, CoasterFan5 requested changes
Positioning of the color picker is a little weird (tested on chromium based). Also color picker element looks out of place.

2024-04-22 09:37 UTC, CoasterFan5 commented
@LeoDog896 lmk what you think

2024-04-22 14:13 UTC, LeoDog896 reviewed
looks good! one review. no clue if its correct.

2024-04-22 14:13 UTC, LeoDog896 commented on src/lib/components/ColorPicker.svelte
> +	export let label = 'Customize color';
title case?

2024-04-22 14:14 UTC, merged