Tooltips
CoasterFan5/Clubsaurus pull request #77
Opened 2024-02-02 19:44 UTC by CoasterFan5

Adds tooltips to any vague button. Fixes #37

2024-02-02 20:30 UTC, LeoDog896 requested changes
drop the console.log statements; also you may want to format the pr; i need to add an eslint rule that bans console.log in src/** some time soon

2024-02-02 20:30 UTC, LeoDog896 commented on src/lib/components/tooltips/tooltip.ts
> +		element.addEventListener('mouseleave', doneHere);
nitpick: you did not let the formatting finish

2024-02-02 20:30 UTC, LeoDog896 commented on src/lib/components/tooltips/tooltip.ts
> +		console.log('done Here');
remove

2024-02-02 20:30 UTC, LeoDog896 commented on src/lib/components/tooltips/tooltip.ts
> +		console.log('startingHere');
remove

2024-02-02 20:30 UTC, LeoDog896 commented on src/lib/components/tooltips/Tooltip.svelte
> +	{#if text}
why is this hidden?

2024-02-02 20:30 UTC, LeoDog896 commented on src/lib/components/tooltips/tooltip.ts
> +		console.log('done Here');
the `console.log`

2024-02-02 20:30 UTC, LeoDog896 commented on src/lib/components/tooltips/tooltip.ts
> +		console.log('startingHere');
the `console.log`

2024-02-02 20:30 UTC, LeoDog896 commented on src/lib/components/tooltips/Tooltip.svelte
> +	{#if text}
if this is *in case* the text doesnt exist, its better to fail fast here

2024-02-02 21:14 UTC, LeoDog896 requested changes
forgor

2024-02-02 21:14 UTC, LeoDog896 commented on src/lib/components/tooltips/tooltip.ts
> +			element.removeEventListener('mouseover', mouseOver);
destory the created svelte component; it has no parent

2024-02-02 21:14 UTC, LeoDog896 commented on src/lib/components/tooltips/tooltip.ts
> +			element.removeEventListener('mouseover', mouseOver);
that way you also dont have to remove the listeners

2024-02-02 21:15 UTC, LeoDog896 requested changes
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role either now or you can make it an issue as a bug

2024-02-03 13:48 UTC, CoasterFan5 commented
> https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role either now or you can make it an issue as a bug

It should be fixed now. The new behavior is as follows: 

- Tooltip will be ignored by screen readers in favor of the title element
- Non-js users can use the title attribute rather than the tooltip. 
- Js users w/o screen readers will see tooltips as normal. 

Lmk if there are any more issues

2024-02-03 17:07 UTC, LeoDog896 requested changes
Can they exit the tooltip by pressing ESC?

2024-02-06 19:20 UTC, LeoDog896 approved these changes

2024-02-06 19:20 UTC, merged